global:
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "yamoahdelvin@gmail.com"
  smtp_auth_username: "yamoahdelvin@gmail.com"
  smtp_auth_password: "hkxz eeza jujn bhpa"

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "web.hook"

receivers:
  - name: "web.hook"
    email_configs:
      - to: "yamoahdelvin@gmail.com"
        subject: "Alert: {{ .GroupLabels.alertname }}"
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}

    slack_configs:
      - api_url: "https://hooks.slack.com/services/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"
        channel: "#alerts"
        title: "Alert: {{ .GroupLabels.alertname }}"
        text: |
          {{ range .Alerts }}
          {{ .Annotations.summary }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "dev", "instance"]
