global:
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "your-email"
  smtp_auth_username: "your-email"
  smtp_auth_password: "gmailAppPassword"

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "alerts"

receivers:
  - name: "alerts"
    email_configs:
      - to: "your-email"
    slack_configs:
      - api_url: "yourSlackApiUrl"
        channel: "#yourSlackChannel"

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "dev", "instance"]
